kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    app: nacos-cluster
  name: nacos-cluster 
  namespace: default
spec:
  replicas: 3
  serviceName: nacos-cluster
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: nacos-cluster
  template:
    metadata:
      name: nacos-cluster
      labels:
        app: nacos-cluster
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm: 
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-cluster
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nacos 
        image: nacos/nacos-server:2.0.0
        imagePullPolicy: Always
        env:
        - name: "JVM_XMS"
          value: "256m"
        - name: "JVM_XMX"
          value: "256m"
        - name: "MYSQL_SERVICE_HOST"
          value: "mysql"
        - name: "MYSQL_SERVICE_DB_NAME"
          value: "nacos"
        - name: "MYSQL_SERVICE_USER"
          value: "nacos"
        - name: "MYSQL_SERVICE_PASSWORD"
          value: "nacos1234"
        - name: "PREFER_HOST_MODE"
          value: "hostname"
        - name: "NACOS_SERVER_PORT"
          value: "8848"
        - name: "NACOS_REPLICAS"
          value: "3"
        - name: "MODE"
          value: "cluster"
        - name: "SPRING_DATASOURCE_PLATFORM"
          value: "mysql"
        - name: "NACOS_SERVERS"
          value: "nacos-cluster-0.nacos-cluster.default.svc.cluster.local:8848 nacos-cluster-1.nacos-cluster.default.svc.cluster.local:8848 nacos-cluster-2.nacos-cluster.default.svc.cluster.local:8848"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: nacos-cluster
  name: nacos-cluster
  namespace: default
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    - port: 7848
      name: old-raft-rpc
      targetPort: 784
  clusterIP: None
  selector:
    app: nacos-cluster
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: nacos-cluster
  name: nacos-cluster-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8848 
    targetPort: 8848
    nodePort: 30848
  selector:
    app: nacos-cluster