kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    app: nacos
  name: nacos
  namespace: default
spec:
  replicas: 3
  serviceName: nacos
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      name: nacos
      labels:
        app: nacos
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - nacos
                topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        layer: frontend
      containers:
        - name: nacos
          image: nacos/nacos-server:2.0.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          env:
            - name: "JVM_XMS"
              value: "256m"
            - name: "JVM_XMX"
              value: "256m"
            - name: "MYSQL_SERVICE_HOST"
              value: "mysql"
            - name: "MYSQL_SERVICE_DB_NAME"
              value: "nacos"
            - name: "MYSQL_SERVICE_USER"
              value: "nacos"
            - name: "MYSQL_SERVICE_PASSWORD"
              value: "nacos1234"
            - name: "PREFER_HOST_MODE"
              value: "hostname"
            - name: "NACOS_SERVER_PORT"
              value: "8848"
            - name: "NACOS_REPLICAS"
              value: "3"
            - name: "MODE"
              value: "cluster"
            - name: "SPRING_DATASOURCE_PLATFORM"
              value: "mysql"
            - name: "NACOS_SERVERS"
              value: "nacos-0.nacos.default.svc.cluster.local:8848 nacos-1.nacos.default.svc.cluster.local:8848 nacos-2.nacos.default.svc.cluster.local:8848"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: nacos
  name: nacos
  namespace: default
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
  clusterIP: None
  selector:
    app: nacos
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nacos
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: nacos
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nacos
                port:
                  number: 8848
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nacos-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nacos