kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: sentinel
  name: sentinel
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      name: sentinel
      labels:
        app: sentinel
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - sentinel
                topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        layer: frontend
      containers:
        - name: sentinel
          image: repository:5000/sentinel
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 500Mi
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: sentinel
  name: sentinel
  namespace: default
spec:
  ports:
    - port: 8858
      targetPort: 8858
  selector:
    app: sentinel
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sentinel
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: sentinel
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentinel
                port:
                  number: 8858
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: sentinel-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sentinel