kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: skywalking
  name: skywalking
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking
  template:
    metadata:
      name: skywalking
      labels:
        app: skywalking
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - skywalking
                topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        layer: frontend
      containers:
        - name: skywalking
          image: repository:5000/skywalking-oap-server
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          command:
            - bash
            - "-c"
            - |
              bash startup.sh
              tail -f ../logs/webapp-console.log
          env:
            - name: SW_CLUSTER
              value: nacos
            - name: SW_SERVICE_NAME
              value: SkyWalking_OAP_Cluster
            - name: SW_CLUSTER_NACOS_HOST_PORT
              value: nacos:8848
            - name: SW_CLUSTER_NACOS_USERNAME
              value: nacos
            - name: SW_CLUSTER_NACOS_PASSWORD
              value: nacos
            - name: SW_CONFIGURATION
              value: nacos
            - name: SW_CONFIG_NACOS_SERVER_ADDR
              value: nacos
            - name: SW_CONFIG_NACOS_SERVER_PORT
              value: "8848"
            - name: SW_CONFIG_NACOS_SERVER_GROUP
              value: skywalking
            - name: SW_CONFIG_NACOS_USERNAME
              value: nacos
            - name: SW_CONFIG_NACOS_PASSWORD
              value: nacos

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: skywalking
  name: skywalking
  namespace: default
spec:
  ports:
    - port: 11800
      targetPort: 11800
      name: "11800"
    - port: 12800
      targetPort: 12800
      name: "12800"
    - port: 8080
      targetPort: 8080
      name: webui
  selector:
    app: skywalking
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-skywalking
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: skywalking
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skywalking
                port:
                  number: 8080
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: skywalking-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: skywalking