spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.edev.trade: INFO
    com.edev.support: INFO
    com.edev.trade.query.dao: DEBUG
    com.edev.support.dao: DEBUG
    com.edev.support.cache: DEBUG
    com.alibaba: WARN
    io.seata: INFO
server:
  port: ${SERVICE_PORT:9002}