kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: edev-alibaba-trade-product
  name: edev-alibaba-trade-product
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edev-alibaba-trade-product
  template:
    metadata:
      name: edev-alibaba-trade-product
      labels:
        app: edev-alibaba-trade-product
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - edev-alibaba-trade-product
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: edev-alibaba-trade-product
        image: repository:5000/edev-alibaba-trade-product:<VERSION>
        imagePullPolicy: Always
        env:
          - name: NACOS_ADDR
            value: "nacos-cluster:8848"

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: edev-alibaba-trade-product
  name: edev-alibaba-trade-product
  namespace: default
spec:
  ports:
  - port: 9003
    targetPort: 9003
  selector:
    app: edev-alibaba-trade-product
