spring:
  cloud:
    sentinel:
      transport:
        dashboard: sentinel:8858
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            rule-type: flow
            username: ${spring.cloud.nacos.discovery.username}
            password: ${spring.cloud.nacos.discovery.password}
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-degrade-rules
            groupId: DEFAULT_GROUP
            rule-type: degrade
            username: ${spring.cloud.nacos.discovery.username}
            password: ${spring.cloud.nacos.discovery.password}
  datasource:
    url: jdbc:mysql://mysql-0.mysql:3306/edevCustomer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: customer
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: redis-0.redis
    port: 6379
    password:
    pool:
      maxActive: 200
      maxWait: -1
      maxIdel: 10
      minIdel: 0
    timeout: 1000
server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include: '*'
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: service-trade-group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      service-trade-group: default
    grouplist:
      default: localhost:8091
    enable-degrade: false
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      cluster: default
      application: seata-server
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group: SEATA_GROUP
      namespace: ""
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group: SEATA_GROUP
      namespace: ""
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}