spring:
  cloud:
    sentinel:
      transport:
        dashboard: sentinel:8858
      eager: true
  datasource:
    url: jdbc:mysql://mysql-0.mysql:3306/edevProduct?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: product
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: redis-0.redis
    port: 6379
    password:
    pool:
      maxActive: 200
      maxWait: -1
      maxIdel: 10
      minIdel: 0
    timeout: 1000
server:
  port: 9003
management:
  endpoints:
    web:
      exposure:
        include: '*'