node {
    def parent = 'edev-alibaba-trade'
    def app = 'edev-alibaba-trade-gateway'
    stage('拉取代码') {
        git "https://gitee.com/mooodo/${parent}.git"
    }
    stage('编译测试') {
        sh """
        cd ${app}
        mvn clean test -Dmaven.test.failure.ignore=true
        """
    }
    stage('制作镜像') {
        sh "/var/jenkins_home/docker.sh ${app}"
        sh """
        cd ${app}
        mvn clean install docker:build -DpushImageTag -Dmaven.test.skip=true
        """
    }
    stage('云端部署') {
        sh """
        cd ${app}
        VER=\$(docker images |grep ${app} |grep -v latest |awk '{print \$2}')
        echo "version:\${VER}"
        sed -i "s/<VERSION>/\${VER}/" "${app}.yaml"
        kubectl apply -f ${app}.yaml
        """
    }
}