kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: edev-trade-order
  name: edev-trade-order
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edev-trade-order
  template:
    metadata:
      name: edev-trade-order
      labels:
        app: edev-trade-order
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - edev-trade-order
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: edev-alibaba-trade-order
        image: repository:5000/edev-alibaba-trade-order:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        env:
          - name: NACOS_ADDR
            value: "nacos:8848"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: edev-trade-order
  name: edev-trade-order
  namespace: default
spec:
  ports:
  - port: 9005
    targetPort: 9005
  selector:
    app: edev-trade-order
